export interface StadiumInfo {
  name: string;
  city: string;
  country: string;
  capacity: number;
  altitude_m: number;
  surface: string;
  is_dome: boolean;
  imageUrl: string;
  wikipediaUrl: string;
}

const W = "https://upload.wikimedia.org/wikipedia/commons/thumb";

export const WC2026_STADIUMS: Record<string, StadiumInfo> = {
  Atlanta: {
    name: "Mercedes-Benz Stadium",
    city: "Atlanta, GA",
    country: "USA",
    capacity: 71000,
    altitude_m: 320,
    surface: "FieldTurf",
    is_dome: true,
    imageUrl: `${W}/1/10/Mercedes_Benz_Stadium_time_lapse_capture_2017-08-13.jpg/1280px-Mercedes_Benz_Stadium_time_lapse_capture_2017-08-13.jpg`,
    wikipediaUrl: "https://en.wikipedia.org/wiki/Mercedes-Benz_Stadium",
  },
  Boston: {
    name: "Gillette Stadium",
    city: "Foxborough, MA",
    country: "USA",
    capacity: 65878,
    altitude_m: 22,
    surface: "Grass",
    is_dome: false,
    imageUrl: `${W}/d/db/Gillette_Stadium_%28Top_View%29.jpg/1280px-Gillette_Stadium_%28Top_View%29.jpg`,
    wikipediaUrl: "https://en.wikipedia.org/wiki/Gillette_Stadium",
  },
  Dallas: {
    name: "AT&T Stadium",
    city: "Arlington, TX",
    country: "USA",
    capacity: 80000,
    altitude_m: 170,
    surface: "AstroTurf",
    is_dome: true,
    imageUrl: `${W}/1/11/Arlington_June_2020_4_%28AT%26T_Stadium%29.jpg/1280px-Arlington_June_2020_4_%28AT%26T_Stadium%29.jpg`,
    wikipediaUrl: "https://en.wikipedia.org/wiki/AT%26T_Stadium",
  },
  Houston: {
    name: "NRG Stadium",
    city: "Houston, TX",
    country: "USA",
    capacity: 72220,
    altitude_m: 15,
    surface: "FieldTurf",
    is_dome: true,
    imageUrl: `${W}/3/3e/Nrg_stadium.jpg/1280px-Nrg_stadium.jpg`,
    wikipediaUrl: "https://en.wikipedia.org/wiki/NRG_Stadium",
  },
  "Kansas City": {
    name: "GEHA Field at Arrowhead Stadium",
    city: "Kansas City, MO",
    country: "USA",
    capacity: 76416,
    altitude_m: 274,
    surface: "Grass",
    is_dome: false,
    imageUrl: `${W}/a/ac/Aerial_view_of_Arrowhead_Stadium_08-31-2013.jpg/1280px-Aerial_view_of_Arrowhead_Stadium_08-31-2013.jpg`,
    wikipediaUrl: "https://en.wikipedia.org/wiki/Arrowhead_Stadium",
  },
  "Los Angeles": {
    name: "SoFi Stadium",
    city: "Inglewood, CA",
    country: "USA",
    capacity: 70240,
    altitude_m: 25,
    surface: "Bermuda grass",
    is_dome: false,
    imageUrl: `${W}/b/b3/SoFi_Stadium_2023.jpg/1280px-SoFi_Stadium_2023.jpg`,
    wikipediaUrl: "https://en.wikipedia.org/wiki/SoFi_Stadium",
  },
  Miami: {
    name: "Hard Rock Stadium",
    city: "Miami Gardens, FL",
    country: "USA",
    capacity: 65326,
    altitude_m: 3,
    surface: "Grass",
    is_dome: false,
    imageUrl: `${W}/c/ce/Hard_Rock_Stadium_for_Super_Bowl_LIV_%2849606710103%29.jpg/1280px-Hard_Rock_Stadium_for_Super_Bowl_LIV_%2849606710103%29.jpg`,
    wikipediaUrl: "https://en.wikipedia.org/wiki/Hard_Rock_Stadium",
  },
  "Mexico City": {
    name: "Estadio Azteca",
    city: "Mexico City",
    country: "Mexico",
    capacity: 87523,
    altitude_m: 2240,
    surface: "Grass",
    is_dome: false,
    imageUrl: `${W}/0/07/Vista_a%C3%A9rea_del_Estadio_Azteca_-_2026_-_02.jpg/1280px-Vista_a%C3%A9rea_del_Estadio_Azteca_-_2026_-_02.jpg`,
    wikipediaUrl: "https://en.wikipedia.org/wiki/Estadio_Azteca",
  },
  Guadalajara: {
    name: "Estadio Akron",
    city: "Zapopan, Jalisco",
    country: "Mexico",
    capacity: 49850,
    altitude_m: 1566,
    surface: "Grass",
    is_dome: true,
    imageUrl: `${W}/1/10/Estadio_Akron_02-07-2022_cabecera_sur_lado_derecho_%283%29.jpg/1280px-Estadio_Akron_02-07-2022_cabecera_sur_lado_derecho_%283%29.jpg`,
    wikipediaUrl: "https://en.wikipedia.org/wiki/Estadio_Akron",
  },
  Monterrey: {
    name: "Estadio BBVA",
    city: "Guadalupe, Nuevo León",
    country: "Mexico",
    capacity: 53500,
    altitude_m: 538,
    surface: "Grass",
    is_dome: false,
    imageUrl: `${W}/5/57/Mexico_Guadalupe_Monterrey_Estadio_BBVA_Bancomer_fifa_world_cup_2026_6.JPG/1280px-Mexico_Guadalupe_Monterrey_Estadio_BBVA_Bancomer_fifa_world_cup_2026_6.JPG`,
    wikipediaUrl: "https://en.wikipedia.org/wiki/Estadio_BBVA",
  },
  "New York/New Jersey": {
    name: "MetLife Stadium",
    city: "East Rutherford, NJ",
    country: "USA",
    capacity: 82500,
    altitude_m: 8,
    surface: "FieldTurf",
    is_dome: false,
    imageUrl: `${W}/0/04/Metlife_stadium_%28Aerial_view%29.jpg/1280px-Metlife_stadium_%28Aerial_view%29.jpg`,
    wikipediaUrl: "https://en.wikipedia.org/wiki/MetLife_Stadium",
  },
  Philadelphia: {
    name: "Lincoln Financial Field",
    city: "Philadelphia, PA",
    country: "USA",
    capacity: 69796,
    altitude_m: 10,
    surface: "Grass",
    is_dome: false,
    imageUrl: `${W}/a/a1/Lincoln_Financial_Field_%28Aerial_view%29.jpg/1280px-Lincoln_Financial_Field_%28Aerial_view%29.jpg`,
    wikipediaUrl: "https://en.wikipedia.org/wiki/Lincoln_Financial_Field",
  },
  "San Francisco": {
    name: "Levi's Stadium",
    city: "Santa Clara, CA",
    country: "USA",
    capacity: 68500,
    altitude_m: 10,
    surface: "Grass",
    is_dome: false,
    imageUrl: `${W}/a/a6/Levi%27s_Stadium_in_February_2016_prior_to_Super_Bowl_50_%2824398261729%29.jpg/1280px-Levi%27s_Stadium_in_February_2016_prior_to_Super_Bowl_50_%2824398261729%29.jpg`,
    wikipediaUrl: "https://en.wikipedia.org/wiki/Levi%27s_Stadium",
  },
  Seattle: {
    name: "Lumen Field",
    city: "Seattle, WA",
    country: "USA",
    capacity: 72000,
    altitude_m: 8,
    surface: "FieldTurf",
    is_dome: false,
    imageUrl: `${W}/5/53/Qwest_Field_North.jpg/1280px-Qwest_Field_North.jpg`,
    wikipediaUrl: "https://en.wikipedia.org/wiki/Lumen_Field",
  },
  Toronto: {
    name: "BMO Field",
    city: "Toronto, ON",
    country: "Canada",
    capacity: 30000,
    altitude_m: 76,
    surface: "Grass",
    is_dome: false,
    imageUrl: `${W}/9/91/Toronto_BMO_Field_in_2024.jpg/1280px-Toronto_BMO_Field_in_2024.jpg`,
    wikipediaUrl: "https://en.wikipedia.org/wiki/BMO_Field",
  },
  Vancouver: {
    name: "BC Place",
    city: "Vancouver, BC",
    country: "Canada",
    capacity: 54500,
    altitude_m: 4,
    surface: "FieldTurf",
    is_dome: true,
    imageUrl: `${W}/f/ff/BC_Place_2015_Women%27s_FIFA_World_Cup.jpg/1280px-BC_Place_2015_Women%27s_FIFA_World_Cup.jpg`,
    wikipediaUrl: "https://en.wikipedia.org/wiki/BC_Place",
  },
};
